import Navbar from "@/components/common/Navbar";
import "./globals.css";
import { Nunito} from "next/font/google";
import Footer from "@/components/common/Footer";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata = {
  title: "Healthy Recipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="nunito.className">
      <body
        className={`bg-neutral-100`} 
      >
        <Navbar />
        <div className="max-w-[1192px] mx-auto">   
           {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
